### ISSUE TITLE
Migration checksum mismatch for migration version 1

### ISSUE THREAD

**Issue by nabeards** [dvasdekis/react-admin-hasura-firebase#12]
I created my own Firebase project and modified the `V1__todo_app.up.sql` file with the new users' info. However, starting up with 'docker-compose up --no-recreate --build' just gives the error `Migration checksum mismatch for migration version 1` from flyway.

Are there some other modifications needed to get this running?

**Comment by dvasdekis** [comment]
This doesn't happen for me. A possible cause could be that you're changing the SQL in the file after having launched and run the Postgres container. See here for more info: https://stackoverflow.com/a/41147917/11867240

Let me know if that fixes it.

**Comment by dvasdekis** [comment]
Managed to recreate by not having a clean database to start with. It's therefore fixable by running `docker container prune -f && docker volume prune -f && docker-compose up --no-recreate --build`
